// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpNM9rz2Fz5ULaqdE_UqqWuBo7AbUnLXY',
    appId: '1:938346714152:web:5acf71e86fbabb895f111d',
    messagingSenderId: '938346714152',
    projectId: 'tiktok-clone-9e352',
    authDomain: 'tiktok-clone-9e352.firebaseapp.com',
    storageBucket: 'tiktok-clone-9e352.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5svqzTCxrBTEnob4FDwrfIDkyMaOQe_4',
    appId: '1:938346714152:android:d3fbf0e5b0b453a85f111d',
    messagingSenderId: '938346714152',
    projectId: 'tiktok-clone-9e352',
    storageBucket: 'tiktok-clone-9e352.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK5cwyH11iwp0_GLvxcBwKvUfeWOUPDLo',
    appId: '1:938346714152:ios:76552ffd4dbdab875f111d',
    messagingSenderId: '938346714152',
    projectId: 'tiktok-clone-9e352',
    storageBucket: 'tiktok-clone-9e352.appspot.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK5cwyH11iwp0_GLvxcBwKvUfeWOUPDLo',
    appId: '1:938346714152:ios:76552ffd4dbdab875f111d',
    messagingSenderId: '938346714152',
    projectId: 'tiktok-clone-9e352',
    storageBucket: 'tiktok-clone-9e352.appspot.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpNM9rz2Fz5ULaqdE_UqqWuBo7AbUnLXY',
    appId: '1:938346714152:web:236e5193ac0cc6b55f111d',
    messagingSenderId: '938346714152',
    projectId: 'tiktok-clone-9e352',
    authDomain: 'tiktok-clone-9e352.firebaseapp.com',
    storageBucket: 'tiktok-clone-9e352.appspot.com',
  );
}
